#!/usr/bin/env bash
#
# Fetch Haskell source from a Stackage snapshot, for use as a benchmark corpus.
#
#   ./bench/fetch-stackage.sh
#   AIHC_CPP_BENCH_CORPUS=dist-newstyle/stackage/lts-24.58/src just bench
#
# The snapshot is pinned below rather than tracking "latest", so that a number
# measured today can be compared against one measured in six months. Bump it
# deliberately, and say so when reporting a change in the results.
#
# Downloads are cached and skipped if already present, so re-running is cheap
# and an interrupted fetch can simply be repeated.
#
set -euo pipefail

snapshot="${AIHC_CPP_STACKAGE_SNAPSHOT:-lts-24.58}"
cache="${AIHC_CPP_STACKAGE_CACHE:-dist-newstyle/stackage/$snapshot}"
# 0 means the whole snapshot (3441 packages for lts-24.58, several GB). The
# default is a stride through the package list, which spans the snapshot
# alphabetically while keeping the download to a few hundred megabytes.
limit="${AIHC_CPP_STACKAGE_PACKAGES:-400}"
jobs="${AIHC_CPP_STACKAGE_JOBS:-8}"

tarballs="$cache/tarballs"
src="$cache/src"
mkdir -p "$tarballs" "$src"

manifest="$cache/packages.txt"
# Only the snapshot's package list is cached. The selection is recomputed every
# run, so changing the package count takes effect without clearing the cache.
if [ ! -s "$manifest.all" ]; then
  echo "fetching package list for $snapshot"
  curl -sSf --max-time 120 "https://www.stackage.org/$snapshot/cabal.config" |
    sed -n 's/^[[:space:]]*\([A-Za-z0-9][A-Za-z0-9-]*\)[[:space:]]*==[[:space:]]*\([0-9][0-9.]*\).*/\1-\2/p' |
    sort -u >"$manifest.all"
fi
total="$(wc -l <"$manifest.all" | tr -d ' ')"
if [ "$limit" -gt 0 ] && [ "$total" -gt "$limit" ]; then
  # Take every Nth package so the sample spans the whole list rather than
  # stopping in the a's. A larger count is a superset of a smaller one, so
  # widening the corpus only downloads what is missing.
  stride=$((total / limit))
  awk -v n="$stride" 'NR % n == 1' "$manifest.all" >"$manifest"
else
  cp "$manifest.all" "$manifest"
fi
echo "selected $(wc -l <"$manifest" | tr -d ' ') of $total packages"

fetch_one() {
  pkg="$1"
  out="$2/$pkg.tar.gz"
  [ -s "$out" ] && return 0
  url="https://hackage.haskell.org/package/$pkg/$pkg.tar.gz"
  # A package present in the snapshot can still be absent from Hackage (it may
  # have been revised or deprecated). Missing ones are skipped, not fatal.
  if curl -sSf --max-time 120 -o "$out.part" "$url" 2>/dev/null; then
    mv "$out.part" "$out"
  else
    rm -f "$out.part"
  fi
}
export -f fetch_one

echo "downloading into $tarballs (jobs: $jobs)"
xargs -P "$jobs" -I{} bash -c 'fetch_one "$@"' _ {} "$tarballs" <"$manifest"

echo "extracting into $src"
extracted=0
for archive in "$tarballs"/*.tar.gz; do
  [ -e "$archive" ] || continue
  name="$(basename "$archive" .tar.gz)"
  [ -d "$src/$name" ] && continue
  tar xzf "$archive" -C "$src" 2>/dev/null || true
  extracted=$((extracted + 1))
done

# Cabal generates a cabal_macros.h per package, defining VERSION_<dep> and
# MIN_VERSION_<dep> for that package's dependencies. A bare source tree has
# none, so every #if MIN_VERSION_foo(...) in the corpus fails to resolve.
#
# One file covering every package in the snapshot stands in for all of them.
# That is more generous than any real build — a package sees only its own
# dependencies, not all 3441 — but it errs towards resolving directives rather
# than skipping them, which is what the benchmark wants: more of the corpus
# actually preprocessed. It is not a substitute for a real build's macros and
# nothing is compiled against it.
#
# Two files are written. cabal_macros.h has every package and is what a module
# resolves if it includes the header by name. cabal_macros_used.h has only the
# packages the corpus actually references, and is the one to prepend to every
# module: a real build pre-includes these macros rather than waiting to be
# asked, but the full file is 1.3MB against an average module of 12KB, so
# prepending it would measure macro-file parsing instead of preprocessing.
generated="$cache/include"
mkdir -p "$generated"
macros="$generated/cabal_macros.h"

echo "generating $macros"
{
  cat <<'HEADER'
/* Generated by bench/fetch-stackage.sh. Do not edit.
 *
 * VERSION_ and MIN_VERSION_ macros for every package in the snapshot, plus the
 * boot packages reported by the local ghc-pkg. Stands in for the per-package
 * cabal_macros.h that Cabal generates during a real build.
 */

#pragma once

#define CURRENT_PACKAGE_KEY "benchmark-corpus"
#define CURRENT_COMPONENT_ID "benchmark-corpus"
#define CURRENT_PACKAGE_VERSION "0"
HEADER

  # Boot packages (base, ghc-prim, template-haskell, ...) are pinned by the
  # compiler rather than the snapshot, so they are absent from cabal.config.
  # MIN_VERSION_base alone is one of the two most referenced macros in real
  # Haskell, so take them from whichever ghc is on PATH.
  if command -v ghc-pkg >/dev/null 2>&1; then
    ghc-pkg list --global --simple-output 2>/dev/null | tr ' ' '\n'
  fi
  cat "$manifest.all"
} | awk '
  /^\/|^ \*|^#|^$/ { print; next }
  {
    entry = $0
    idx = match(entry, /-[0-9][0-9.]*$/)
    if (idx == 0) next
    name = substr(entry, 1, idx - 1)
    version = substr(entry, idx + 1)
    gsub(/[^A-Za-z0-9_]/, "_", name)
    if (name in seen) next
    seen[name] = 1

    split(version, part, ".")
    a = part[1] + 0; b = part[2] + 0; c = part[3] + 0

    printf "\n/* package %s-%s */\n", name, version
    printf "#define VERSION_%s \"%s\"\n", name, version
    printf "#define MIN_VERSION_%s(major1,major2,minor) (\\\n", name
    printf "  (major1) <  %d || \\\n", a
    printf "  (major1) == %d && (major2) <  %d || \\\n", a, b
    printf "  (major1) == %d && (major2) == %d && (minor) <= %d)\n", a, b, c
    printf "#define MIN_TOOL_VERSION_%s(major1,major2,minor) (\\\n", name
    printf "  (major1) <  %d || \\\n", a
    printf "  (major1) == %d && (major2) <  %d || \\\n", a, b
    printf "  (major1) == %d && (major2) == %d && (minor) <= %d)\n", a, b, c
  }
' >"$macros"

used="$generated/cabal_macros_used.h"
echo "generating $used"
# The packages any module actually names in a MIN_VERSION_ or VERSION_ macro.
grep -rhoE '\b(MIN_VERSION|VERSION|MIN_TOOL_VERSION)_[A-Za-z0-9_]+' "$src" --include='*.hs' 2>/dev/null |
  sed -E 's/^(MIN_TOOL_VERSION|MIN_VERSION|VERSION)_//' |
  sort -u >"$generated/used-packages.txt"
awk '
  NR == FNR { used[$0] = 1; next }
  /^\/|^ \*|^#pragma|^$/ { print; next }
  /^\/\* package / { keep = 0 }
  /^#define (VERSION|MIN_VERSION|MIN_TOOL_VERSION)_/ {
    name = $2
    sub(/^(VERSION|MIN_VERSION|MIN_TOOL_VERSION)_/, "", name)
    sub(/\(.*$/, "", name)
    keep = (name in used)
  }
  /^#define CURRENT_/ { print; next }
  keep { print }
' "$generated/used-packages.txt" "$macros" >"$used"

modules="$(find "$src" -name '*.hs' | wc -l | tr -d ' ')"
cat <<EOF

snapshot:  $snapshot
packages:  $(find "$src" -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ') extracted ($extracted new)
modules:   $modules .hs files
size:      $(du -sh "$src" | cut -f1)

macros:    $(grep -c '^#define MIN_VERSION_' "$macros") packages ($(du -h "$macros" | cut -f1)) in $macros
prelude:   $(grep -c '^#define MIN_VERSION_' "$used") packages ($(du -h "$used" | cut -f1)) in $used

Run the benchmark against it with:

  AIHC_CPP_BENCH_CORPUS=$src \\
  AIHC_CPP_BENCH_INCLUDE=bench/include:$generated \\
  AIHC_CPP_BENCH_PRELUDE=$used \\
  just bench
EOF
